// versions/svelte4/src/lib/DockItem.svelte
<script lang="ts">
	import { interpolate } from 'popmotion';
	import type { AppID } from 'src/types';
	import { spring } from 'svelte/motion';

	export let appID: AppID;
	export let mouseX: number | null;

	let el: HTMLImageElement;

	const baseWidth = 57.6;
	const distanceLimit = baseWidth * 6;
	const beyondTheDistanceLimit = distanceLimit + 1;
	const distanceInput = [
		-distanceLimit,
		-distanceLimit / 1.25,
		-distanceLimit / 2,
		0,
		distanceLimit / 2,
		distanceLimit / 1.25,
		distanceLimit,
	];
	const widthOutput = [
		baseWidth,
		baseWidth * 1.1,
		baseWidth * 1.618,
		baseWidth * 2.618,
		baseWidth * 1.618,
		baseWidth * 1.1,
		baseWidth,
	];

	let distance = beyondTheDistanceLimit;

	const widthPX = spring(baseWidth, {
		damping: 0.38,
		stiffness: 0.1,
	});

	$: $widthPX = interpolate(distanceInput, widthOutput)(distance);

	let width: string;
	$: width = `${$widthPX / 16}rem`;

	let raf: number;

	function animate(mouseX: number) {
		if (el && mouseX !== null) {
			const rect = el.getBoundingClientRect();

			// get the x coordinate of the img DOMElement's center
			// the left x coordinate plus the half of the width
			const imgCenterX = rect.left + rect.width / 2;

			// difference between the x coordinate value of the mouse pointer
			// and the img center x coordinate value
			const distanceDelta = mouseX - imgCenterX;
			distance = distanceDelta;
			return;
		}

		distance = beyondTheDistanceLimit;
	}

	$: raf = requestAnimationFrame(() => animate(mouseX));
</script>

<section>
	<button class="dock-button">
		<img
			bind:this={el}
			class="app-icon"
			src="/app-icons/{appID}/256.png"
			alt=""
			style="width: {width};"
		/>
	</button>
</section>

<style>
	.dock-button {
		height: 100%;
		width: auto !important;

		cursor: default !important;

		transition: all 200ms ease-in;

		transform-origin: bottom;

		display: flex;
		flex-direction: column;
		justify-content: flex-end;
	}

	button {
		color: inherit;
		text-decoration: none;
		vertical-align: middle;

		border: 0;
		border-radius: 0;

		outline: 0;

		margin: 0;
		padding: 0;

		display: inline-flex;
		align-items: center;
		justify-content: center;

		position: relative;

		user-select: none;

		appearance: none;

		background-color: transparent;

		-webkit-tap-highlight-color: transparent;

		&:not(:disabled) {
			cursor: pointer;
		}
	}

	.app-icon {
		width: 57.6px;
		height: auto;
	}
</style>

// versions/react/src/DockItem.tsx
import useRaf from '@rooks/use-raf';
import { motion, type MotionValue, useMotionValue, useSpring, useTransform } from 'framer-motion';
import { useRef } from 'react';
import { AppID } from './types';

type DockItemProps = {
	mouse_x: MotionValue<number | null>;
	app_id: AppID;
};

const base_width = 57.6;
const distance_limit = base_width * 6;
const beyond_the_distance_limit = distance_limit + 1;
const distance_input = [
	-distance_limit,
	-distance_limit / 1.25,
	-distance_limit / 2,
	0,
	distance_limit / 2,
	distance_limit / 1.25,
	distance_limit,
];
const width_output = [
	base_width,
	base_width * 1.1,
	base_width * 1.414,
	base_width * 2,
	base_width * 1.414,
	base_width * 1.1,
	base_width,
];

export function DockItem({ mouse_x, app_id }: DockItemProps) {
	const img_ref = useRef<HTMLImageElement>(null);

	const distance = useMotionValue(beyond_the_distance_limit);

	const width_px: MotionValue<number> = useSpring(
		useTransform(distance, distance_input, width_output),
		{
			stiffness: 1300,
			damping: 82,
		}
	);

	const width = useTransform(width_px, (width) => `${width / 16}rem`);

	useRaf(() => {
		const el = img_ref.current;
		const mouse_x_val = mouse_x.get();
		if (el && mouse_x_val !== null) {
			const rect = el.getBoundingClientRect();

			const img_center_x = rect.left + rect.width / 2;

			// difference between the x coordinate value of the mouse pointer
			// and the img center x coordinate value
			const distance_delta = mouse_x_val - img_center_x;
			distance.set(distance_delta);
			return;
		}

		distance.set(beyond_the_distance_limit);
	}, true);

	return (
		<section>
			<button className='dock-button'>
				<motion.img
					ref={img_ref}
					className='app-icon'
					src={`/app-icons/${app_id}/256.png`}
					draggable={false}
					style={{ width, willChange: 'width' }}
				/>
			</button>
		</section>
	);
}
